#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# update event
#
event_templates('nethserver-sogo-thunderbird-update', qw(
    /etc/httpd/conf/httpd.conf
));

event_actions('nethserver-sogo-thunderbird-update', qw(
    initialize-default-databases     00
    nethserver-sogo-build-integrator 40
));

event_actions ('hostname-modify' , qw(
    nethserver-sogo-build-integrator 40
));

event_services('nethserver-sogo-thunderbird-update', qw(
    httpd reload
));

