#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# update event
#
event_templates('nethserver-sogo-thunderbird-update', qw(
    /etc/httpd/conf/httpd.conf
));

event_actions('nethserver-sogo-thunderbird-update', qw(
    initialize-default-databases     00
    nethserver-sogo-thunderbird-conf 30
    nethserver-sogo-build-integrator 40
    runlevel-adjust 50
    firewall-adjust 60
));

event_services('nethserver-sogo-thunderbird-update', qw(
    httpd reload
));

#
# uninstall event
#
event_actions('nethserver-sogo-thunderbird-uninstall', qw(
    nethserver-sogo-thunderbird-uninstall 30
    runlevel-adjust 50
    firewall-adjust 60
));

